
default: test_all

#Note: nonzero output doesn't indicate necessarily error.
test_all: gl_plot_continuous plot_n_hist

ContinuousSeq:
	sh test.sh ContinuousSeq

plot_n_hist:
	sh test.sh plot_n_hist

