
default: test_all

#Note: nonzero output doesn't indicate necessarily error.
test_all: gl_plot_continuous plot_n_hist

gl_plot_continuous:
	sh test.sh gl_plot_continuous

plot_n_hist:
	sh test.sh plot_n_hist

