
default: test_all

#Note: nonzero output doesn't indicate necessarily error.
test_all: ContinuousSeq FancyKeyedData plot_n_hist

ContinuousSeq:
	sh test.sh ContinuousSeq
FancyKeyedData:
	sh test.sh FancyKeyedData

plot_n_hist:
	sh test.sh plot_n_hist

